[logs]
  [logs.logs_collected]
    [logs.logs_collected.files]
      [[logs.logs_collected.files.collect_list]]
      file_path = "/proc/self/fd/1"
      log_group_name = "/ecs/lamp-app-logs"
      log_stream_name = "apache-access-log"
      timezone = "UTC"
      
      [[logs.logs_collected.files.collect_list]]
      file_path = "/proc/self/fd/2"
      log_group_name = "/ecs/lamp-app-logs"
      log_stream_name = "apache-error-log"
      timezone = "UTC"
      
      [[logs.logs_collected.files.collect_list]]
      file_path = "/proc/self/fd/2"
      log_group_name = "/ecs/lamp-app-logs"
      log_stream_name = "php-error-log"
      timezone = "UTC"
